server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-game
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug